package fr.univavignon.ceri.deskmap;

import javafx.fxml.FXML;
import javafx.scene.control.Alert;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.Button;

import javafx.scene.control.SplitPane;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;
import javafx.scene.control.MenuItem;
import javafx.scene.control.TextArea;

import javafx.scene.input.KeyEvent;

public class MainViewController {
	@FXML
	private SplitPane splitPane;
	@FXML
	private TextField cityName;
	@FXML
	private TextField fromName;
	@FXML
	private TextField toName;
	@FXML
	private ComboBox fromCombo;
	@FXML
	private ComboBox toCombo;
	@FXML
	private Button search;
	@FXML
	private Button reset;
	@FXML
	private TextArea itineraire;
	@FXML
	private MenuItem AboutUs;

	// Event Listener on TextField[#cityName].onKeyPressed
	@FXML
	public void cityNameInput(KeyEvent event) { //verify if other text fields are not empty to activate button
		if(  cityName.getText() != null && !( cityName.getText().trim().isEmpty() )  ) {
			search.setDisable(false); 
			}
		else {search.setDisable(true); }
	}
	// Event Listener on TextField[#fromName].onKeyPressed
	@FXML
	public void fromVerif(KeyEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#toName].onKeyPressed
	@FXML
	public void toVerif(KeyEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#search].onAction
	@FXML
	public void search(ActionEvent event) {
		System.out.println("Search clicked");
	}
	// Event Listener on Button[#reset].onAction
	@FXML
	public void reset(ActionEvent event) {
		System.out.println("reset clicked");
		cityName.clear();
		fromName.clear();
		toName.clear();
		fromCombo.valueProperty().set("");
		toCombo.valueProperty().set("");
	}
	// Event Listener on Button[#AboutUs].onAction
	@FXML
	public void AboutUs(ActionEvent event) {
		Alert alert = new Alert(AlertType.INFORMATION);
		alert.setTitle("About Us");
		alert.setHeaderText(null);
		alert.setContentText("Mohamed BENYAMNA, Yanis LABRAK, Quantin, Zihao ZHENG are students in CERI-Avignon");

		alert.showAndWait();
	}
	
	
}
